### ISSUE TITLE
A question about batchsize

### ISSUE THREAD

**Issue by JoyHuYY1412** [Jin-Ying/GTA-Seg#2]
Hi Ying, thank you for your codes and the great work! I have one question about the batch size. 

In the config, the batch size is 3 per GPU. So for each GPU (4 in total), it will have 3 labeled, 3 unlabeled for the teacher model, and 3 unlabeled for the GTA model.

Do I understand right? Appreciate your reply.

**Comment by Jin-Ying** [comment]
I think it is right. Thank you
