### ISSUE TITLE
Data spilt for Pascal VOC12.

### ISSUE THREAD

**Issue by zhibotian** [Jin-Ying/GTA-Seg#3]
Does the data split of Pascal VOC12 in GTA-Seg is same as [U2PL](https://github.com/Haochen-Wang409/U2PL) ? And if you follow the U2PL ,all the experiments are 100% high-quality labels within the AUG experiments, including 2646, 1323, 732, 366, maybe it is unfair. Could you please report results of the spilt same as [CPS](https://github.com/charlesCXK/TorchSemiSeg/tree/main/DATA/pascal_voc/subset_train_aug)？ 
Thanks！

**Comment by Jin-Ying** [comment]
Yes, it is the same as U2PL. We have compared our method with U2PL and previous methods both on the orignal and augmented set of PASCAL VOC. Therefore, all the comparison results are fair. You can use the split in CPS to further evaluate our methods. Thank you for your comments.
