### ISSUE TITLE
关于论文中公式6的理解

### ISSUE THREAD

**Issue by Fly-Yun-Maker** [Jin-Ying/GTA-Seg#4]
您好，感谢您卓越的工作，我不太能理解公式6中的每个像素权重的意义，i和j应该表示这个图片中的像素位置，那为什么还要在公式中加入两个对i和对j的求和符号。希望得到您的回复。

**Comment by VecentPotter** [comment]
明明是一个求和对i求和，另一个求和对j求和。

**Comment by Jin-Ying** [comment]
> 明明是一个求和对i求和，另一个求和对j求和。

是的，公式中求和的对象不同。感谢您对工作的关注。
